version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - auth_template:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  auth_template:
