services:
  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - auth_template:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  auth_template:
